name: GHA Usage Audit
on:
  workflow_dispatch:
# Uncomment if you wish to have the job scheduled to run every day (of the month, every week and every day in the week)
#  schedule:
#    - cron: "0 3 * * *" # Runs at 03:00 AM (UTC) every day

jobs:
  gha-usage-minutes-report:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Actions Usage Audit
        uses: fergusmacd/github-action-usage@daff7e5517914546a1e39fcc22f476e1471853f6 # use a commit SHA
        # pass user input as arguments
        with:
#          organisation: ${{secrets.ORGANISATION}}
          organisation: rsymo-org
          gitHubAPIKey: ${{secrets.GITHUBAPIKEY}} # default token in GitHub Workflow
          loglevel: debug # error, not required, change to debug if misbehaving
          raisealarmremainingminutes:  100 # not required, defaults to 100

